### ISSUE TITLE
oToken settlement price doesn't show on Avalanche

### ISSUE THREAD

**Issue by yukamend** [antoncoding/gamma-portal#121]
oToken settlement price doesn't show on Avalanche, instead '-' is displayed. 
![image](https://user-images.githubusercontent.com/90453245/167223851-a8653af6-b1d7-4d6d-8d62-1ddd66efb1b6.png)

**Comment by antoncoding** [comment]
can you confirm that the prices are indeed submitted from the pricers? 
It might be bot missing submissions.
